application: warworldsmmo
version: 1
runtime: python27
api_version: 1
threadsafe: true

libraries:
- name: jinja2
  version: latest

handlers:
- url: /img
  static_dir: static/img

- url: /css
  static_dir: static/css

- url: /js
  static_dir: static/js

- url: /data
  static_dir: static/data

- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico

- url: /mapreduce(/.*)?
  script: mapreduce.main.APP
  login: admin

- url: /api/v1(/.*)?
  script: api_v1.app

- url: /admin(/.*)?
  script: admin.app

- url: /tasks/sector(/.*)?
  script: tasks.sector.app
  login: admin

- url: /tasks/empire(/.*)?
  script: tasks.empire.app
  login: admin

- url: /.*
  script: frontend.app

