application: warworldsmmo
version: 1
runtime: python27
api_version: 1
threadsafe: true

libraries:
- name: jinja2
  version: 2.6

builtins:
- deferred: on

inbound_services:
- warmup

# We can't include it because it doesn't support Python 2.7/threadsafe=true
#includes:
#- mapreduce/include.yaml

handlers:
- url: /img
  static_dir: static/img

- url: /css
  static_dir: static/css

- url: /js
  static_dir: static/js

- url: /data
  static_dir: static/data

- url: /intel/
  static_dir: static/intel

- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico

# These two are copied (and slightly modified from mapreduce/include.yaml so
# it can support threading:true
- url: /mapreduce/pipeline/images
  static_dir: mapreduce/lib/pipeline/ui/images
- url: /mapreduce(/.*)?
  script: mapreduce.main.APP
  login: admin

- url: /api/v1(/.*)?
  script: api_v1.app

- url: /admin(/.*)?
  script: admin.app

- url: /tasks/sector(/.*)?
  script: tasks.sector.app
  login: admin

- url: /tasks/empire(/.*)?
  script: tasks.empire.app
  login: admin

- url: /tasks/stats(/.*)?
  script: tasks.statistics.app
  login: admin

- url: /_ah/.*
  script: tasks.builtin.app

- url: /.*
  script: frontend.app

